In [2]:
import numpy as np

In [6]:
list1=[2,3,4]
list2=[5,6,7]

In [7]:
np.array(list1)+np.array(list2)

array([ 7,  9, 11])

In [8]:
arr_str=['Mercedes',6,'Audi','Ferrari','Tesla']
arr_num=(5,4,6,7,3)

In [14]:
matrix=[[1,2]
        ,[4,5],
        [1,8]]

In [15]:
type(matrix)

list

In [16]:
matrix

[[1, 2], [4, 5], [1, 8]]

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
ar=np.arange(0,30)
print(ar.reshape(3,10))
print(ar.reshape(2,15))
print(ar.reshape(10,3))
print(ar.reshape(5,6))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
