In [1]:
import numpy as n

In [2]:
n.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
n.zeros(shape=(5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
n.ones(shape=(4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
n.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [8]:
n.linspace(start=1,stop=10,num=4,dtype=int)

array([ 1,  4,  7, 10])

## creating random numbers in Numpy

In [10]:
n.random.rand(5)

array([0.92353974, 0.43813344, 0.59687191, 0.40011234, 0.33662922])

In [25]:
num_arr=n.random.randint(low=1,high=100,size=7)
num_arr

array([63, 73, 30, 27,  7, 36, 88])

In [26]:
num_arr

array([63, 73, 30, 27,  7, 36, 88])

In [27]:
num_arr[1:4]

array([73, 30, 27])

In [28]:
num_arr[-1]

88

NameError: name 'np' is not defined